import onnxruntime as ort
import tensorflow as tf
import numpy as np
import glob

# Load normalized calibration image for ONNX
test_files = glob.glob('calibration_data_sample_data_nchw/*.npy')
test_input_nchw = np.load(test_files[0]) # (1, 3, 224, 224) - NORMALIZED

session = ort.InferenceSession('optixai_dr_model.onnx')
input_name = session.get_inputs()[0].name
onnx_output = session.run(None, {input_name: test_input_nchw})[0]

# Generate raw [0, 255] pixels
test_input_nhwc = np.transpose(test_input_nchw, (0, 2, 3, 1))
std = np.array([0.229, 0.224, 0.225], dtype=np.float32)
mean = np.array([0.485, 0.456, 0.406], dtype=np.float32)
raw_pixels_float = ((test_input_nhwc * std) + mean) * 255.0
raw_pixels_uint8 = np.clip(np.round(raw_pixels_float), 0, 255).astype(np.uint8)

# Now, let's look at the model generated by onnx2tf
tflite_path = 'optixai_tflite_model/optixai_dr_model_full_integer_quant.tflite'
interpreter = tf.lite.Interpreter(model_path=tflite_path)
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()[0]
output_details = interpreter.get_output_details()[0]

scale, zero_point = input_details['quantization']
print(f"Quantization scale: {scale}, zero_point: {zero_point}")

# If the model baked in normalization, we just need to pass the raw pixels!
# Wait, if input is int8, we map uint8 [0, 255] to int8 [-128, 127] by subtracting 128.
tflite_input_int8 = (raw_pixels_uint8.astype(np.int32) - 128).astype(np.int8)

interpreter.set_tensor(input_details['index'], tflite_input_int8)
interpreter.invoke()
tflite_output = interpreter.get_tensor(output_details['index'])
out_scale, out_zero_point = output_details['quantization']
tflite_output_float = (tflite_output.astype(np.float32) - out_zero_point) * out_scale

print("ONNX (FP32):  ", onnx_output)
print("TFLite (Raw): ", tflite_output_float)
print("Max Diff:     ", np.max(np.abs(onnx_output - tflite_output_float)))
